#cloud-config

write_files:
  - path: /etc/netplan/eth1.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth1:
            dhcp4: true

runcmd:
  - [ netplan, apply ]

manage_resolv_conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'
    - '1.1.1.1'

users:
  - name: XXXXSERVER_USERXXXX
    passwd: 'XXXXSERVER_USER_PASSWORDXXXX'
    groups: [ sudo ]
    shell: /bin/bash
    lock_passwd: false

    ssh_authorized_keys:
      - 'XXXXSSH_PUBLIC_KEYXXXX'

ssh_pwauth: false

ssh_keys:
  XXXXALGORITHMXXXX_private: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      XXXXSSH_PRIVATE_KEYXXXX
      -----END OPENSSH PRIVATE KEY-----

timezone: 'XXXXTIMEZONEXXXX'
hostname: XXXXDATABASE_HOSTNAMEXXXX
manage_etc_hosts: true

bootcmd:
  - cloud-init-per once setlocales /bin/sed -i '/en_GB.UTF/s/\(^# \)\(.*$\)/\2/g' /etc/locale.gen
  - cloud-init-per once /bin/echo LANG="en_GB.UTF-8" > /etc/default/locale

locale: en_GB
keyboard:
  layout: gb

write_files:
- encoding: b64
  content: XXXXDATABASE_CONFIGURATIONXXXX
  owner: root:root
  path: /home/XXXXSERVER_USERXXXX/.ssh/database_configuration_settings.dat.gz
  permissions: '0644'
- encoding: b64
  content: XXXXBUILDSTYLES_SETTINGSXXXX
  owner: root:root
  path: /home/XXXXSERVER_USERXXXX/.ssh/buildstyles.dat.gz
  permissions: '0644'
- content: /home/XXXXSERVER_USERXXXX
  owner: root:root
  path: /home/homedir.dat
  permissions: '0644'
- content: |
    ClientAliveInterval 60
    ClientAliveCountMax 2
  path: /home/XXXXSERVER_USERXXXX/.ssh/config
  owner: 'root:root'
  permissions: '0600'


package_update: true
package_upgrade: true

packages:
  - git
  - network-manager 
  - software-properties-common
  - jq
  - rsync
  - cron
#XXXXMARIADB_SERVERXXXX  - mariadb-server
#XXXXPOSTRGESQL_SERVERXXXX  - postgresql-server
#XXXXMARIADB_CLIENTXXXX  - mariadb-client
#XXXXPOSTRGESQL_CLIENTXXXX  - postgresql-client

runcmd:
 # - '/usr/sbin/netplan apply'
  - '/bin/cp /etc/ssh/ssh_host_rsa_key /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX'
  - '/bin/cp /etc/ssh/ssh_host_rsa_key.pub /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX.pub'
  - '/bin/chmod 600 /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX'
  - '/bin/chmod 600 /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX.pub'
  - '/usr/bin/git clone https://XXXXGIT_PROVIDER_DOMAINXXXX/XXXXINFRASTRUCTURE_REPOSITORY_OWNERXXXX/adt-database-scripts.git /home/XXXXSERVER_USERXXXX/clone'
  - '/bin/mv /home/XXXXSERVER_USERXXXX/clone/* /home/XXXXSERVER_USERXXXX && /bin/rm -r /home/XXXXSERVER_USERXXXX/clone'
  - '/usr/bin/gzip -d /home/XXXXSERVER_USERXXXX/.ssh/database_configuration_settings.dat.gz'
  - '/bin/cp /home/XXXXSERVER_USERXXXX/.ssh/database_configuration_settings.dat /home/XXXXSERVER_USERXXXX/runtime/database_configuration_settings.dat'
  - '/usr/bin/gzip -d /home/XXXXSERVER_USERXXXX/.ssh/buildstyles.dat.gz'
  - '/bin/cp /home/XXXXSERVER_USERXXXX/.ssh/buildstyles.dat /home/XXXXSERVER_USERXXXX/runtime/buildstyles.dat'
  - '/usr/bin/find /home/XXXXSERVER_USERXXXX -type d -exec chmod 755 {} \;' 
  - '/usr/bin/find /home/XXXXSERVER_USERXXXX -type f -exec chmod 750 {} \;'
  - '/bin/chmod 600 /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX'
  - '/bin/chmod 600 /home/XXXXSERVER_USERXXXX/.ssh/id_XXXXALGORITHMXXXX_AGILE_DEPLOYMENT_BUILD_KEY_XXXXBUILD_IDENTIFIERXXXX.pub'
  - '/usr/bin/chown -R XXXXSERVER_USERXXXX:root /home/XXXXSERVER_USERXXXX'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^PasswordAuthentication.*/PasswordAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^PermitRootLogin.*/PermitRootLogin no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^#PermitRootLogin.*/PermitRootLogin no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^#KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^#ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^AddressFamily.*/AddressFamily inet/g' {} +'
  - '/usr/bin/find /etc/ssh -name '*' -type f -exec sed -i 's/^#AddressFamily.*/AddressFamily inet/g' {} +'
  - '/usr/bin/systemctl restart ssh'
  #cloud-init has a maximum user data size of 16384 bytes for data passed to an instance. so I do these runcmds to preserve some capacity
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallPackageManager.sh' 
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallGo.sh &' 
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallDatastoreTools.sh' 
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallFirewall.sh' 
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallDatabase.sh'
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/db.sh &'
  - 'export HOME=/home/XXXXSERVER_USERXXXX && /bin/sh ${HOME}/installscripts/InstallEmailUtil.sh'
